apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "workflow-shared-service.fullname" . }}-backend
  labels:
    {{- include "workflow-shared-service.labels" . | nindent 4 }}
data:
  DJANGO_DEBUG: {{ .Values.backend.env.DJANGO_DEBUG | quote }}
  DJANGO_ALLOWED_HOSTS: {{ .Values.backend.env.DJANGO_ALLOWED_HOSTS | quote }}
  CORS_ALLOWED_ORIGINS: {{ .Values.backend.env.CORS_ALLOWED_ORIGINS | quote }}
  USE_SQLITE: {{ .Values.backend.env.USE_SQLITE | quote }}
  POSTGRES_HOST: {{ .Values.backend.env.POSTGRES_HOST | quote }}
  POSTGRES_PORT: {{ .Values.backend.env.POSTGRES_PORT | quote }}
  POSTGRES_DB: {{ .Values.backend.env.POSTGRES_DB | quote }}
  POSTGRES_USER: {{ .Values.backend.env.POSTGRES_USER | quote }}
  POSTGRES_PASSWORD: {{ .Values.backend.env.POSTGRES_PASSWORD | quote }}
